// Writes web/wasm.js and web/presets.js. Run by web/build.sh.
import { readFileSync, writeFileSync } from "node:fs";

const here = new URL(".", import.meta.url);
const read = (path) => readFileSync(new URL(path, here));

const wasm = read("mesh.wasm").toString("base64");
writeFileSync(new URL("wasm.js", here),
  `// Generated by web/build.sh from web/mesh.wasm. Don't edit.\nexport default "${wasm}";\n`);

// mm_presets in core/meshmonitor.c: {"Name", "#background", "#dots", "#lines", "#packets"},
const source = read("../core/meshmonitor.c").toString();
const block = source.match(/const mm_preset mm_presets\[\] = \{([\s\S]*?)\n\};/);
if (!block) throw new Error("mm_presets not found in core/meshmonitor.c");
const presets = [...block[1].matchAll(/\{\s*"([^"]+)",\s*"(#[0-9a-fA-F]{6})",\s*"(#[0-9a-fA-F]{6})",\s*"(#[0-9a-fA-F]{6})",\s*"(#[0-9a-fA-F]{6})"\s*\}/g)]
  .map(([, name, background, dots, lines, packets]) => ({ name, colors: { background, dots, lines, packets } }));
if (presets.length === 0) throw new Error("no presets parsed from core/meshmonitor.c");
writeFileSync(new URL("presets.js", here),
  `// Generated by web/build.sh from mm_presets in core/meshmonitor.c. Don't edit.\nexport default ${JSON.stringify(presets, null, 2)};\n`);
