// Generated by web/build.sh from mm_presets in core/meshmonitor.c. Don't edit.
export default [
  {
    "name": "Default",
    "colors": {
      "background": "#0b0b0a",
      "dots": "#eeebe4",
      "lines": "#eeebe4",
      "packets": "#f06a2a"
    }
  },
  {
    "name": "Meshtastic",
    "colors": {
      "background": "#0a0f0b",
      "dots": "#e8f5ec",
      "lines": "#67ea94",
      "packets": "#67ea94"
    }
  },
  {
    "name": "Green terminal",
    "colors": {
      "background": "#000000",
      "dots": "#33ff66",
      "lines": "#33ff66",
      "packets": "#ccffcc"
    }
  },
  {
    "name": "Amber terminal",
    "colors": {
      "background": "#0a0700",
      "dots": "#ffb000",
      "lines": "#ffb000",
      "packets": "#fff1c4"
    }
  },
  {
    "name": "Paper",
    "colors": {
      "background": "#f4f1ea",
      "dots": "#1d1c1a",
      "lines": "#1d1c1a",
      "packets": "#e8591a"
    }
  }
];
